export const WOQL_EDITOR_THEME = 'mdn-like'
export const WOQL_VIEWER_THEME = 'mdn-like'
export const HIDE_QUERY_EDITOR = 'Hide Query Editor'
export const SHOW_QUERY_EDITOR = 'Show Query Editor'
export const SHOW_VIEW_EDITOR = 'Show View Editor'
export const HIDE_VIEW_EDITOR = 'Hide View Editor'
export const QUERY_SUBMIT = 'Run Query'
export const EDIT_THIS_VERSION = "Edit this version"
export const LANGUAGE_NAMES = {js: "WOQL.js", python: "WOQL.py", json: "JSON-LD"}
export const LANGUAGE_DROPDOWN = "Language Views"