export const CREATE_VIEW = 'Create Database'
export const CREATE_OPTIONS = 'Create Options'
export const COPY_OPTIONS = 'Copy Options'
export const COPY_TYPES = 'Copy Types'
export const COPY = 'Copy'
export const CREATE_REMOTE = 'Create Database on terminusdb.com'
export const CREATE_LOCAL = 'Create Database Locally'
export const CLONE_LOCAL = 'Clone from Local Database'
export const CLONE_REMOTE = 'Clone from Remote Database'


export const CREATE_DB = 'Create Database'
export const COPY_DB = 'Copy Database'
export const LOCAL = 'Local'
export const REMOTE = 'Remote'
export const CLONE = 'Clone'
export const FORK = 'Fork'
