export const LIST_OF_DATABASE_QUERY = 'LIST_OF_DATABASE_QUERY'
export const LIST_OF_DATABASE_ID = 'LIST_OF_DATABASE_ID'
export const SCHEMA_LIST_OF_CLASSES_QUERY = 'SCHEMA_LIST_OF_CLASSES_QUERY'
export const SCHEMA_LIST_OF_PROPERTIES_QUERY = 'SCHEMA_LIST_OF_PROPERTIES_QUERY'


// query to get from createTerminusDb
export const GET_USER_LIST = "GET_USER_LIST"
export const GET_USER_ACCESS_FOR_DB = "GET_USER_ACCESS_FOR_DB"
