export const RENDER_TYPE_TABLE = 'RENDER_TYPE_TABLE';
export const RENDER_TYPE_MAPS = 'RENDER_TYPE_MAPS';
export const RENDER_TYPE_GRAPH = 'RENDER_TYPES_GRAPH';
export const RENDER_TYPE_SNIPPET = 'RENDER_TYPE_SNIPPET';
