export const SUCCESS = 'SUCCESS'
export const ERROR = 'ERROR'
export const SUCCESS_COLOR = 'success'
export const VIO_COLOR = 'warning'
export const ERROR_COLOR = 'danger'
export const WARNING_COLOR = 'warning'
