export const TERMINUS_IMAGE_BASE = "https://assets.terminusdb.com/terminusdb-console/images/"
export const DELETE_ICON = TERMINUS_IMAGE_BASE + "delete.png"
export const COWDUCK_HELP_ICON = TERMINUS_IMAGE_BASE + "cowDuckHelp.png"
export const DIALOGUE_BACKGROUND = TERMINUS_IMAGE_BASE + "card-shape-3.svg"
export const LOADING_SPINNER = TERMINUS_IMAGE_BASE + "loading.svg"
export const MASCOT_COLOR = TERMINUS_IMAGE_BASE + "Mascot-Color.png"
export const COMING_SOON = TERMINUS_IMAGE_BASE + "comingSoon.png"
export const GRAPHDB = TERMINUS_IMAGE_BASE + "create-locally-1.png"
export const HUBDB = TERMINUS_IMAGE_BASE + "cowduck-space.png"
export const HUBLOGO = TERMINUS_IMAGE_BASE + "terminushub.png"

//export const HUBLOGO = "file:\\C\Users\kevin\ngit\terminusdb-web-assets\terminusdb-console\images\terminushub.png"
