export const CREATEDB_TITLE = "New Database"
export const DBLIST_TITLE  = "My Databases"
export const CREATE_FIRSTDB_CSS = "color-primary alert"
export const CREATE_FIRSTDB = ""
export const DBLIST_HEADER_CSS = "some-old-header-css"