import { library } from '@fortawesome/fontawesome-svg-core';
import { faUser, faPowerOff, faClock, faCheckCircle, faPenAlt, faUserFriends, faStarOfLife, faInfo,
    faInfoCircle, faCodeBranch, faBomb, faStamp, faInfinity, faTimesCircle, faHdd, faExclamationCircle, faTools,
    faPlayCircle, faCaretSquareLeft, faCaretSquareRight, faTrashAlt, faUpload, faDownload, faShareAlt, faStopCircle, faBook, faBackward, faFileAlt, faCopy, faRecycle, faSync} from '@fortawesome/free-solid-svg-icons';

export const initFontLib = library.add(faUser,
    faPowerOff,
    faClock,
    faCheckCircle,
    faInfoCircle,
    faExclamationCircle,
    faUserFriends,
    faStarOfLife,
    faPenAlt,
    faInfo,
    faTimesCircle,
    faPlayCircle,
    faCaretSquareLeft,
    faCaretSquareRight,
    faHdd,
    faCodeBranch,
    faInfinity,
    faStamp,
    faTools,
    faBomb,
    faTrashAlt,
    faUpload,
    faDownload,
    faShareAlt,
    faStopCircle,
    faBook,
    faBackward,
    faFileAlt,
    faCopy,
    faSync
);
