name: Build and release
on:
  push:
    branches:
      - dev
      - canary
      - rc

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: |
        if [ $(echo "${{ github.ref }}" | grep -P "canary|rc") ]; then
            mv console/env-production console/.env
        elif [ $(echo "${{ github.ref }}" | grep -P "dev") ]; then
            mv console/env-development console/.env
        fi
    - run: |
        if [ $(echo "${{ github.ref }}" | grep -P "dev|canary") ]; then
            BRANCH="${GITHUB_REF##*/}"
            bash .ci/install_node_project.sh 'https://github.com/terminusdb/terminusdb-client-js.git' "$BRANCH" "terminusdb-client"
            bash .ci/install_node_project.sh 'https://github.com/terminusdb/terminusdb-react-components.git' "$BRANCH" "terminusdb-react-components"
        fi
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_TOKEN }}
        export_default_credentials: true

    - run: npm run build

    - run: |
        if [ $(echo "${{ github.ref }}" | grep -P "dev|canary") ]; then
            bash ".ci/publish_gcloud.sh" "${GITHUB_REF##*/}"
        fi
